# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'BuzMe' do

    pod 'Parse’
    pod 'GoogleMaps', '~> 1.10.5'

end

